name: uSleep
main: es.xdec0de.usleep.USPMain
author: xDec0de_
version: 1.3.1
softdepend: [Essentials]
commands:
  usleep:
    usage: /<command>
    description: Main command of the plugin.
    aliases: [us]
  bedtp:
    usage: /<command>
    description: Teleport to the bed of a player.