# |------------------------------------------------------------------------| #
# | #                                                                    # | #
# | #                   -----------------------------                    # | #
# | #                   | uSleep v2.0.0 by xDec0de_ |                    # | #
# | #                   -----------------------------                    # | #
# | #                                                                    # | #
# |------------------------------------------------------------------------| #

Features:
  Updater:
    Console: true
    Players: true
  InstantSleep:
    Enabled: true
  PercentSleep:
    Enabled: true
    Percentage: 50
    Ignored:
      AFK: true
      Vanished: true
    Cooldown: 5
  Actionbar: true
Permissions:
  Reload: "usp.reload"
  Updater:
    Notify: "usp.updater.notify"
    Check: "usp.updater.check"
  BedTP:
    Self: "usp.bed"
    Other: "usp.bed.other"
  Sleep:
    Instant: "usp.sleep.instant"
    Percent: "usp.sleep.percent"
Sounds: 
  Sleep:
    Ok: "BLOCK_NOTE_BLOCK_PLING"
    Error: "BLOCK_NOTE_BLOCK_BASS"
    Leave: "BLOCK_NOTE_BLOCK_BASS"
  NextDay:
    Percent: "ENTITY_PLAYER_LEVELUP"
    Instant: "ENTITY_PLAYER_LEVELUP"
